services:  
  connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: connect
    depends_on:
      - cassandra
    volumes:
      - ./jars:/etc/kafka-connect/jars
      - ./conn-config:/workarea
    command: [ "connect-standalone", "/workarea/worker.properties", "/workarea/cassandra_conn.properties" ]
  

  cassandra:
    image: proxy.replicated.com/proxy/mission-control/559669398656.dkr.ecr.us-west-2.amazonaws.com/engops-shared/hcd/staging/hcd:1.1.0
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - DS_LICENSE=accept
    volumes:
      - ./cassandra-data:/var/lib/cassandra
      - ./scripts/:/custom_scripts/
    healthcheck:
      test: ["CMD-SHELL", "cqlsh cassandra -e 'DESCRIBE KEYSPACES;'"]
      interval: 20s
      timeout: 10s
      retries: 5


  # cassandra:
  #   image: cassandra:latest
  #   ports:
  #     - "9042:9042"
  #   environment:
  #     - CASSANDRA_CLUSTER_NAME=TestCluster
  #   volumes:
  #     - ./cassandra-data:/var/lib/cassandra
  #     - ./scripts/:/custom_scripts/
  #   healthcheck:
  #     test: ["CMD-SHELL", "cqlsh cassandra -e 'DESCRIBE KEYSPACES;'"]
  #     interval: 20s
  #     timeout: 10s
  #     retries: 5
